# <playerName> - player name
# <c > - text color

# config version
config_version: 1

# messages
messages:
  helpMessage: This is a <c5>CyberSleepPlugin. <cf>The plugin helps to skip boring nights!
  enterBedMessage: <c7>Good night <playerName>!
  exitBedMessage: <c7>Good morning <playerName>!
  reloadMessage: <c5>CyberSleepPlugin <cf>reloaded!

sleeping_bar:
  title: <c9>Sleeping
  color: blue


max_percent_of_sleeping_players: 0.3 # диопозон от 0 до 1