# <playerName> - имя игрока
# c - ключевой знак для указания цвета текста

# сообщения
messages:
  helpMessage: This is a c5CyberSleepPlugin. cfThe plugin helps to skip boring nights!
  enterBedMessage: c7Good night <playerName>!
  exitBedMessage: c7Good morning <playerName>!
  reloadMessage: c5CyberSleepPlugin cfreloaded!

sleeping_bar:
  title: c9Sleeping
  color: blue

max_percent_of_sleeping_players: 0.3 # диопозон от 0 до 1