# <playerName> - player name
# <c > - specifying the color
# <c0> - black
# <c1> - dark blue
# <c2> - dark green
# <c3> - dark aqua
# <c4> - dark red
# <c5> - dark purple
# <c6> - gold
# <c7> - gray
# <c8> - dark gray
# <c9> - blue
# <ca> - green
# <cb> - aqua
# <cc> - red
# <cd> - light purple
# <ce> - yellow
# <cf> - white

# config version
config_version: 1

# messages
messages:
  helpMessage: This is a <c5>CyberSleepPlugin. <cf>The plugin helps to skip boring nights!
  enterBedMessage: <c7>Good night <playerName>!
  exitBedMessage: <c7>Good morning <playerName>!
  reloadMessage: <c5>CyberSleepPlugin <cf>reloaded!

sleeping_bar:
  title: <c9>Sleeping
  color: blue # blue, red, yellow, green, pink, purple - available colors

max_percent_of_sleeping_players: 0.3 # range from 0 to 1